container:
  image: golang:1.10

test_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
  get_script: go get -t -v ./...
  vet_script: go vet -v ./...
  test_script: go test -v ./...

deploy_docker_builder:
  only_if: $CIRRUS_BRANCH == "master"
  depends_on: test
  environment:
    DOCKER_USER_NAME: ENCRYPTED[81138e1a6e2213ac2c2ab7fe39ac91c304928046e984a2a947aab3ed3860802b9a95a72206ba0769f00bbe4f21a84c2d]
    DOCKER_PASSWORD: ENCRYPTED[61d7105b225c7aae7fabe036dff68618f31ec89ac6ccd16b00d9de69c80ceb7aec02e3c5b9c19aa24379553177fc5b00]
  build_script:
    - docker build --tag cirrusci/google-storage-proxy:latest .
  push_script:
    - docker login --username $DOCKER_USER_NAME --password $DOCKER_PASSWORD
    - docker push cirrusci/google-storage-proxy:latest