container:
  image: golang:1.10

test_task:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
  get_script: go get -t -v ./...
  vet_script: go vet -v ./...
  test_script: go test -v ./...
